### ISSUE TITLE
Send user event data to API

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#103]

**Comment by jviotti** [comment]
@mkorakakis is currently working on this feature request, though the progress is blocked due to the following change required in https://github.com/resin-io/resin-event-log:

[ ] Support for promises in hooks, since Resin Settings Storage uses promises for saving/accessing the interaction uuid and not waiting for completion might create race conditions.

Currently, @zewish is working on these changes.

**Comment by jviotti** [comment]
@zewish Any updates regarding the module?

**Comment by zewish** [comment]
Hey @jviotti, I released the updated version of the module yesterday, there are some hooks and also the "interaction ID" is removed - read the module is simplified. It should be okay to be used now. Please update to version 0.0.4 though.
