### ISSUE TITLE
Possible perms issue with default resin projects directory.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#109]
one issue i noticed with the default folder location is that there might be a permission problem for some users.
```
resin-io:resin-wifi-connect hobochild$ git push resin master -f
error: unable to create directory for .git/refs/remotes/resin/master

error: update_ref failed for ref 'refs/remotes/resin/master': Cannot lock the ref 'refs/remotes/resin/master’.

 ```

**Comment by jviotti** [comment]
I have a theory about this issue, although I need to investigate this further:

`device init` needs `sudo` in order to write the image to the drive, and therefore creates an application directory that doesn't have write permissions for the current user.

Possible solutions:

- Create the directory as the user instead of `root`.
- Tweak the permissions of the directory after it's creation.

**Comment by shaunmulligan** [comment]
The quickstart, when it creates a folder and associates it, that folder is owned by the root user, so then on OSX, it always wants me to used sudo, even to commit, etc.

**Comment by jviotti** [comment]
This happens with the cache as well. If you download an image with `sudo`, that image file is owned by root.
