### ISSUE TITLE
improve error message when running `resin device init` without --application

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#196]
currently the error message is this:
```
resin:~ hobochild$ sudo resin device init
Command failed: /bin/sh -c git config --get remote.resin.url
```

**Comment by jviotti** [comment]
This can mean two things:

- The user don't have `git` installed on his machine.
- When running `device init` without an `--application` option, `device init` assumes the current directory is a `git` repository and tries to get the application name from the remote.

The improvements to these error conditions should be applied in https://github.com/resin-io/resin-vcs:

- [ ] Check that a directory is a `git` repo before running any command, otherwise throw an error.
- [ ] Check that the `git` binary is accessible in the path before running any command, otherwise throw an error.

The errors will automatically be propagated to the CLI.

**Comment by jviotti** [comment]
Turns out we already check that the `git` binary is accessible.

**Comment by jviotti** [comment]
Checking that a directory is a `git` repo is being fixed in https://github.com/jviotti/gitwrap/pull/2.

**Comment by jviotti** [comment]
Fixed. Please reinstall the Resin CLI to get the latest changes.
