### ISSUE TITLE
friendlier error messages when running quickstart with out sudo

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#221]
Currently if you run quickstart without permissions, it lets you select and app, and device type and then throws an error about permissions when it tries to access the cached .img files. I suggest checking perms when the command is run and prompting users to run the command with elevated perms.

**Comment by jviotti** [comment]
Due to the problem of cache and `.git` belonging to `root` in some edge cases, both `quickstart` and `device init` *do not* require `sudo` anymore. You will be prompted for a password only when really necessary, e.g: when burning the sdcard.

Since your cache already belongs to `root`, I suggest removing and running `quickstart` without `sudo` from now on.

> I suggest checking perms when the command is run and prompting users to run the command with elevated perms.

This could work in some cases, but switching between permissions within the same command turns to be very tricky, since the process has to re-execute to gain extra privileges.

Can you paste the actual error that you get?

I suggest improving such error and probably warning the user when running `quickstart`/`device init` as `root`, although it's arguably the expected behaviour: if you run a command as another user, every file it creates will belong to that user.

**Comment by jviotti** [comment]
I just noticed a problem with the current solution:

- Since we don't require elevated permissions on the mentioned commands, Windows users will not get a message to run the command from an administrator command prompt anymore, but the command will fail during device initialisation given that we don't elevate permissions on Windows.

I'll open a new issue for this.

**Comment by jviotti** [comment]
Permissions are now asked only when necessary, and `quickstart` doesn't require `sudo` anymore.
