### ISSUE TITLE
Explain the password question.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#239]
Can we explain that the password that the cli is asking for during quickstart and device init is the administrative password? Just because it could be a little confusing to the user.

**Comment by jviotti** [comment]
@shaunmulligan There are three things we can do here:

1- Print a message **above** the `sudo` prompt. For example:

```sh
The CLI requires your password to access the connected drive.
Password:
```

2- Modify the prompt itself. For example:

```sh
Type your password to burn the image to your drive:
```

3- A combination of both approaches mentioned before.

***

I think I'm more towards the first option since it allows us to be more verbose, otherwise a long prompt would be annoying for some users.

What do you think?

**Comment by shaunmulligan** [comment]
Yeah, I like option 1 better, lets go with that for now
