### ISSUE TITLE
Issue with resin cache for raspberry-pi

### ISSUE THREAD

**Issue by mscharley** [resin-io/resin-cli#327]
Every so often I get the following issue:

```
Getting device operating system for raspberry-pi
Z_BUF_ERROR: unexpected end of file
```

Simply flushing the resin cache manually seems to fix it.

**Comment by jviotti** [comment]
Hi @mscharley ,

Thanks for reaching out. This means that for some reason the download stopped in the middle and the received data is not complete. Usually this happens because of a flaky internet connection, although I'm aware we've been having some issues on the component that serves the image recently, which we're still tracking down.

For now, until the issue is really resolved, I guess the only solution is to clear the cache and retry until it works. Once its in the cache, it will be reused so you shouldn't have to deal with the download again.

**Comment by mscharley** [comment]
The issue is that I'm not getting a flaky download. The first download works fine then when it should be loading from the cache I get that error instead.

**Comment by mscharley** [comment]
If I flush the cache to force a download it starts working again.

**Comment by jviotti** [comment]
@mscharley What's the exact size of the file (`$HOME/.resin/cache/raspberry-pi.img`)?

**Comment by mscharley** [comment]
```
$ ls -l ~/.resin/cache/raspberry-pi.img
-rw-r--r--  1 matthewscharley  staff  1593835520 Mar 16 14:10 /Users/matthewscharley/.resin/cache/raspberry-pi.img
$ md5 ~/.resin/cache/raspberry-pi.img
MD5 (/Users/matthewscharley/.resin/cache/raspberry-pi.img) = bb1031d7ef10ef562065922a04df8c4c
```

**Comment by jviotti** [comment]
@mscharley I've encountered a few download timeouts at the middle of the process by repeatedly running `quickstart`. I'll raise this with the rest of the Resin.io team in case there are known issues on the component that serves the images.

I see that the size and checksum match, so I'm not sure what could be going on. Some things I'd try:

- Try running `quickstart` with `DEBUG=true` in order to get more information about the error:

```sh
$ DEBUG=true resin quickstart
```

- Try mounting `$HOME/.resin/cache/raspberry-pi.img` in OS X. Does that work?

**Comment by mscharley** [comment]
```
$ DEBUG=true resin quickstart
? Select an application DocketPrinterStage (raspberry-pi)
Getting device operating system for raspberry-pi
Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Gitter: https://gitter.im/resin-io/chat
```

**Comment by jviotti** [comment]
@mscharley This is really weird. I can't reproduce it. So this is the same image that has the correct size and checksum? 

Is there a chance you can upload this "broken" image somewhere (e.g: Dropbox) so I can experiment with it?

Also, what Resin CLI version are you running?

**Comment by mscharley** [comment]
I was running 0.3.0 before, I just updated to 2.7.0 and completely deleted my `~/.resin` folder and I'm still having the same issue.

My cache folder: https://equiem-artifacts.s3.amazonaws.com/resin-cache.tar.gz

**Comment by jviotti** [comment]
@mscharley Thanks for sharing this. I sadly still can't reproduce, even with your same image, which makes me wonder if there is something in your environment causing this issue.

What OS and NodeJS version are you running?

**Comment by jviotti** [comment]
Also, can you reproduce the issue by running the following command instead of `quickstart`?

```sh
$ resin os download raspberry-pi --output rpi.img
```

**Comment by mscharley** [comment]
* OS - OS X 10.10.5
* Node.js - v5.7.1

Using OS download I initially got this message:

```
QUOTA_EXCEEDED_ERR: Unknown error.
    at LocalStorage.setItem (/usr/local/lib/node_modules/resin-cli/node_modules/node-localstorage/LocalStorage.js:198:15
)
    at /usr/local/lib/node_modules/resin-cli/node_modules/resin-settings-storage/build/storage.js:49:25
    at tryCatcher (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/method.
js:31:24)
    at Object.exports.set (/usr/local/lib/node_modules/resin-cli/node_modules/resin-settings-storage/build/storage.js:45
:24)
    at /usr/local/lib/node_modules/resin-cli/node_modules/resin-token/build/token.js:82:20
    at tryCatcher (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/promise.js
:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/mai
n/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Gitter: https://gitter.im/resin-io/chat
```

After clearing the cache folder though I got:

```
[~/.resin]$ DEBUG=true resin os download raspberry-pi --output ~/.resin/cache/rpi.img
Getting device operating system for raspberry-pi
Downloading Device OS [========================] 100% eta 0s  
The image was downloaded successfully
[/.resin]$ DEBUG=true resin os download raspberry-pi --output ~/.resin/cache/rpi.img
Getting device operating system for raspberry-pi
Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Gitter: https://gitter.im/resin-io/chat
```

**Comment by jviotti** [comment]
Hi @mscharley,

Thanks a lot for the incredible amount of help you're providing with this issue, very appreciated! We'll hopefully get to the bottom of it soon :)

I've investigated the `QUOTA_EXCEEDED_ERR ` error, which seems to be completely unrelated: We use `node-localstorage` to manage to files inside the data directory (defaults to `$HOME/.resin`). The module tries to mimic the browser and puts a 5MB maximum quota by default. This means that having many files in `$HOME/.resin` (apart from `$HOME/.resin/cache`) can trigger this. I believe you put other files apart from `token` and `cache/` there that caused this. I'll disable the default quota to fix this. 

Regarding the original issue, we're having some server-side issues when serving the images that causes the following error on the SDK end to end test suites:

```
Message:
    invalid stored block lengths
Details:
    errno: -3
    code: Z_DATA_ERROR
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
Stack:
Error: invalid stored block lengths
  at Zlib._binding.onerror (zlib.js:296:17)
```

The image is then incomplete, and attempts to get it back return the error you're facing (I can reproduce this way). The Resin.io backend team is already working on it (they think its a race condition).

The weird thing is that based on your output, the image reaches 100% and `The image was downloaded successfully` is reported, meaning its not the issue we see in our CI servers. The fact that you uploaded your image file here, and I tested it out without any issue confuses me further.

Let me explain how the download currently works: We make an HTTP GET request to the Image Maker (the backend component that serves the image), which responds with the actual image with `gzip` compression. We pipe the data through a `zlib` transform stream that uncompresses the stream. The stream is then piped to `$HOME/.resin/cache/<device-type>.img` and the passed output location **at the same time**. If there is a cached image, instead of making an HTTP request to download the image, we copy it from the cache to the output location.

So if your download completes, it means that `zlib` uncompresses the image correctly. When you get it from the cache, it **should not** involve `zlib`, since the image is already uncompressed, but by seeing your output, you get a `zlib` error, which makes no sense.

What I would like to try is downloading the file directly with our low-level module called [resin-request](https://github.com/resin-io-modules/resin-request), which the SDK internally uses, to test the download independently on the storage. I've created the following gist: https://gist.github.com/jviotti/82f9148328b54184b102, which you can run with the following commands:

```sh
$ cd path/to/downloaded/gist
$ npm install
$ node index.js ~/Downloads/rpi.img
```

Another good thing to try would be `os download` with different device types, like `raspberry-pi2`, `parallella`, `beaglebone-black`, etc.

Let me know how it goes!

**Comment by jviotti** [comment]
Also, if you can, give the CLI a go in other computer as well.

**Comment by jviotti** [comment]
I've fixed the quota error in `resin-settings-storage`: https://github.com/resin-io/resin-settings-storage/pull/10. Thanks to semver, re-installing the CLI should get you the fix.

**Comment by mscharley** [comment]
One of my coworkers just had the same issue too. He's running OS X as well, though he's running El Capitan.

**Comment by mscharley** [comment]
That gist ran twice successfully. The output file is not gzipped (neither is the file in `~/.resin/cache`).

Downloading the rpi2 image twice gives the same failures even after updating to resin-cli v3.0.2.

**Comment by jviotti** [comment]
@mscharley I'll do some more testing on this. In the gist I sent, the package is being unzipped on the fly (that's why the result is not compressed) and does not save the file in the cache (that's the responsibility of another component which makes use of the module I'm using in the gist).

If the gist works with no trouble, I believe the issue then resides in [resin-image-manager](https://github.com/resin-io/resin-image-manager). I'll investigate and post back my results.

**Comment by jviotti** [comment]
Hi @mscharley ,

I just worked on this with a user that was hitting this issue. The issue was gone by upgrading NodeJS to version v5.10.1 from v5.6.0 solved the issue. Can you confirm this as well?

**Comment by mscharley** [comment]
Hmm, just the update to node didn't help but after reinstalling and flushing out the `~/.resin` folder the issue seems to have gone away. Not sure what to make of that, but there we go.
