### ISSUE TITLE
resin local docs

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-cli#479]
We don't have `resin local` docs on the repo. Looks like they used to be generated with capitano, @lekkas did you give this a try? 

I don't mind looking into it just wanted to check if there are major hurdles?

**Comment by craig-mulligan** [comment]
For reference https://github.com/resin-os/resinos/pull/267

**Comment by lekkas** [comment]
Hey @craig-mulligan ,

Right, I missed to create/publish them when adding `resin local` commands. Normally `npm run doc` produces docs from comments, however I just tried to run it and it didn't produce docs for `resin local` commands because these are grouped in a folder (`actions/local`) and `extras/capitanodoc/index.coffee` doesn't seem to scan nested folders for actions.

So this seems like a quick fix in `extras/capitanodoc/index.coffee` if you 're up for it a PR 🤘 !

**Comment by craig-mulligan** [comment]
Hey @lekkas yep it was a quick fix 👍 see #480

**Comment by lekkas** [comment]
Rad! 🎉
