### ISSUE TITLE
Inconsistent rules for application names

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-cli#519]
On the dashboard we can use upper case letters in application names, but not in resin-cli:

```
? Select a name for the application SenseSnake
Application name may only contain lowercase characters, digits and one or more dashes. It may not start or end with a dash.

```

**Comment by lekkas** [comment]
@CameronDiver what particular cli command is this message from? 

I guess it's from `resin local push`, in in the previous rdt context the 'application' referred to a standalone container running on an unmanaged resinOS device. So I guess we can change these messages to refer to `application container` to make it more clear, because these limitations apply to container names in the docker API (can't find the actual docs now)

**Comment by CameronDiver** [comment]
Ah ok that makes more sense (it was `resin local push`), I had figured it was supposed to have parity with the dashboard but it makes sense that it would be docker rules.

**Comment by pimterry** [comment]
As far as we know there's actually no need for a container name on local push at all (#682), so let's close this in favour of removing the name entirely.
