### ISSUE TITLE
npm install leave behind full raspberrypi3 image file in node_modules

### ISSUE THREAD

**Issue by imrehg** [resin-io/resin-cli#564]
Running the npm install script from the tar package, a command like this:

```
npm install --global --only=production --user root --prefix "pkg/usr" resin-cli-5.11.0.tgz
```

I end up with a `raspberrypi3-v2.0.6+rev1.prod.img` and `raspberrypi3-config.json` in the `usr/lib/node_modules/resin-cli/tmp/` directory after the install (that's an extra 1.7GB).

Is that intended to be left behind by `npm install`?

This is for `5.11.0`, don't think it was like that before.

**Comment by pimterry** [comment]
@imrehg I can't reproduce this locally, and I'm be very surprised if this was caused by resin-cli itself (which doesn't even include the string `raspberrypi3`, except in its docs). Are you sure this wasn't a local download, present in your local dir when you packaged the `tgz`, and bundled up by npm?

**Comment by imrehg** [comment]
@pimterry looks like it was just 5.11.0, check the http://registry.npmjs.org/resin-cli/-/resin-cli-5.11.0.tgz file (the one that my AUR package is working from), it contains `package/tmp/raspberrypi3-v2.0.6+rev1.prod.img`.

Seems to be fixed in 5.11.1.

**Comment by pimterry** [comment]
Ah, good spot, thanks! Looks like @emirotin published this, and happened to have a pi image in his dir at the time, so it got included and published.

We should work out how to avoid this in future though. @emirotin thoughts? Autopublishing will improve this quite a bit, since it takes our local environments out of the picture, but we haven't set it up yet on the CLI. We could do that? Or we could move to an explicit `files` param in package.json in the meantime?

**Comment by emirotin** [comment]
Woah!
I thought why the pubulishing was so slow...
Explicit `files` can be tricky too of course if we decide to add some new folder and publish the broken module then.
Let's go for autopublishing?

**Comment by pimterry** [comment]
We do now have autopublishing, so issues like this shouldn't come back.
