### ISSUE TITLE
"Unauthorized" uploading image to shared project

### ISSUE THREAD

**Issue by memolipd** [resin-io/resin-cli#594]
It seems to work on Resin Applications I have made myself but throws the error when pushing to any applications a different developer has made and shared with me.

This seems like a bug, since using other means I can push images to applications created by other developers and shared with me.

**Comment by pimterry** [comment]
Hi @memolipd, this is due to a bug in our builder, which checked only if you were the owner of an application, for local pushes, not anybody with access to it. We've got the basics of a fix working now, just finishing it up at the moment - I'll ping back here once it's resolved and deployed. Thanks for the report!

**Comment by pimterry** [comment]
Hi @memolipd, I'm afraid we forgot to update you here - we added support for this in August. If you want to deploy to a collaborators app, you can now use `resin deploy $APP_OWNER/$APP_NAME` and that should work as if it were your own. I've just opened a PR to also mention this in the documentation for the command, so it hopefully shouldn't catch people out in the future!

Thanks again for the report, let us know if you have any more trouble.
