### ISSUE TITLE
The -y flag needs to be at the end of the command which is unusal

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/resin-cli#63]
It seems that the flag has to be put last in the command, which is very unusual:-

```
[~]$ resin -y app rm foo                                                                
Usage: resin [COMMAND] [OPTIONS]

Commands:

    version                       	output the version number
    help [command...]             	show help
    login [token]                 	login to resin.io
    logout                        	logout from resin.io
    signup                        	signup to resin.io
    whoami                        	get current username
    app create <name>             	create an application
    apps                          	list all applications
    app <name>                    	list a single application
    app rm <name>                 	remove an application
    app restart <name>            	restart an application
    app associate <name>          	associate a resin project
    init                          	init an application
    devices                       	list all devices
    devices supported             	list all supported devices
    device rename <name> [newName]	rename a resin device
    device init [device]          	initialise a device with resin os
    device <name>                 	list a single device
    device rm <name>              	remove a device
    device identify <uuid>        	identify a device with a UUID
    device await <name>           	await for a device to become online
    drives                        	list available drives
    note <|note>                  	set a device note
    preferences                   	open preferences form
    keys                          	list all ssh keys
    key add <name> [path]         	add a SSH key to resin.io
    key <id>                      	list a single ssh key
    key rm <id>                   	remove a ssh key
    envs                          	list all environment variables
    env add <key> [value]         	add an environment variable
    env rename <id> <value>       	rename an environment variable
    env rm <id>                   	remove an environment variable
    logs <uuid>                   	show device logs
    os download <name>            	download device OS
    os install <image> [device]   	write an operating system image to a device
    examples                      	list all example applications
    example clone <id>            	clone an example application
    example <id>                  	list a single example application
    plugins                       	list all plugins
    plugin install <name>         	install a plugin
    plugin update <name>          	update a plugin
    plugin rm <name>              	remove a plugin
    update                        	update the resin cli

Global Options:

    --quiet, -q         	quiet (no output)
    --project, -j <path>	project path
    --version, -v       	output the version number
    --no-color          	disable colour highlighting

[~]$ resin app -y rm foo                                                                
ID: 123456789
APP NAME: foo
DEVICE TYPE: raspberry-pi2
GIT REPOSITORY: <redacted>
COMMIT: <redacted>
[~]$ resin app rm -y foo
Application not found: rm
[~]$ resin app rm foo -y
[~]$ # Succeeded.
```

I'd expect that any of the first 3 possibilities would work, and the final one would fail :)

**Comment by jviotti** [comment]
It turns out this is quite tricky to implement, given that there is no unambiguous way to parse the commands. For example:

    resin -y app rm foo 

The command line parser could interpret that you're calling the command `app rm foo`, and you're passing a boolean command option. Also, it could interpret that you're calling the command `rm foo` and the command option '-y=app'.

The same reasoning applies to the other examples, so basically the problem is that we don' t have a way to know in advance that a command option is boolean or takes a parameter.

Possible solutions:

- Move the commands to colon syntax (`app:rm`). In that case we can decide that it makes no sense to pass an option parameter that contains a colon, which could be problematic since other users can expect colon separated option parameters.
- The command options that take parameters should be passed as `--option=value` instead of `--option value`.
- Try to interpret the command intention, search the registered commands for a match, take the match's options and interpret the options according to their definition, which sounds quite complex.

**Comment by lorenzo-stoakes** [comment]
I am not overly worried about the `resin -y app rm foo` form, I am fine with `resin app:rm -y foo` etc.

I think the best solution is to have --option=value, where if there's no '=' you interpret as a boolean input. Additionally the single-dash form could purely be for boolean options.

Having flags at the end of a CLI command is really non-standard, in fact many commands expect the final argument to specify e.g. a file and will reject this form, and I certainly can't think of any CLI I've seen that restricts you from putting flags elsewhere.

I think we'd really be confusing users here if we carried on forcing that. That combined with non-specific help screens, just the general overall help and then one for the top-level command (also I couldn't see -y mentioned anywhere) would make using the tool frustrating. For one it took me a while to find the correct form of -y, so whatever choices we make me need to move away from that!

**Comment by jviotti** [comment]
I agree with your concerns, however the minority of the command line tools handle options in the form of `--option=value`.

I've been checking some other CLIs and they seems to solve the problem by not letting a command have more than one word, e.g: `resin app-rm` instead of `resin app rm`. That'd allow us to assume `argv[1]` is always the command name. In case we implement this change, I'd like the separator to be `-`, in order to be consistent with 'git' and many other well known tools.

The problem with this approach is that Capitano promotes this feature and a lot of work has been made to support this kind of multiple-word commands (it's one of they key points of Capitano), but I guess this not really critical since not many applications rely on Capitano.

**Comment by jviotti** [comment]
I actually don't think that forcing one word commands will help us very much.

Consider the following command:

    $ resin app-rm -y MyApp

Given that we know the second word is the command, we omit `resin app-rm` and proceed to parse `-y myApp`, but then again it is not clear if `MyApp` is a command argument, or an argument to the `-y` option.

**Comment by jviotti** [comment]
However, if we know `app-rm` is the command, we can check the options defined for that specific command and use that information to qualify options as boolean/non boolean. So I think this solution would fix the issue. What do you think?

**Comment by Page-** [comment]
Isn't this just a case of having boolean params, if it doesn't expect a value then a value after it would be part of the main command rather than a flag, eg `apt-get -y install -q a -q b` whilst an odd way of writing it, it'd be equivalent to `apt-get install a b -qqy`

**Comment by jviotti** [comment]
@Page- Sure, the problem is that options are defined per command, and if we get something like:

    $ resin app -y rm MyApp

We can interpret as:

    $ resin app rm -y=MyApp # matches resin app <name> or resin app rm <name> with a missing app error.
    $ resin app -y=rm MyApp # matches resin app <name>
    $ resin app rm -y MyApp # matches resin app rm <name>
    $ resin -y app rm MyApp # matches resin rm <app> or resin app rm <name>

Therefore, we can't be sure which command it matches to see the list of options it accepts an interpret them accordingly.

**Comment by Page-** [comment]
We either do not know of `-y`, in which case it's an invalid arg for the given command and we look for further matches, or we know that `-y` is a boolean flag, meaning it can be either `` for false or `-y` for true.

You could also allow `-y=false`, `-y=true` if you want, but `-y ArbitraryArg` would still be invalid, so we know it's not part of the flag.

**Comment by jviotti** [comment]
Currently Capitano doesn't require option arguments to match for a command to be executed. If you pass an unknown command option to a known command, the unknown option is discarded, so we can't rely on that to determine a match.

In order to enforce that command options also match the signature, we would need to assume an option is either boolean or not.

For example `resin app -y rm MyApp`:

- If we interpret as `resin app rm MyApp` with a boolean `yes` option, then it`d match `app rm` correctly.
- If we interpret as `resin app MyApp` with `--yes=rm` it'd match `app`, but `app` doesn't accept a `--yes` option, therefore it's not considered a match (what if it did accept such an option? We'd have no way to determine which one the user intended to execute, unless we opt for precedence match, which may be confusing sometimes).

In this case the correct answer is `app rm`.

Therefore we could determine all possible interpretations of a command and try to match them in turns with the recognised commands. Enforcing the options would help getting an unambiguous answer most of the time, but if the 2 possible commands share the same options, there is no way to know we're choosing correctly.

**Comment by jviotti** [comment]
I think the most straightforward way to fix this issue is to require non boolean command line options to have an equal sign.

The one-word command solution helps, but still requires us to have knowledge of a command specific options to determine a match, which brings us to the same problem again.

Minimist, the parser we're using in Capitano supports an option to force command options to require an equal sign if not boolean, however it doesn't enforce this on single hyphenated options for some reason. I've opened an issue (https://github.com/substack/minimist/issues/52), which if implemented, would allow us a one line fix to this problem in Capitano.

**Comment by jviotti** [comment]
Moved this issues to https://github.com/resin-io/capitano/issues/29.
