### ISSUE TITLE
Update resin-preload to support jetson-tx2

### ISSUE THREAD

**Issue by zvin** [resin-io/resin-cli#705]
Also remove the --dont-detect-flasher-type-images option which is no longer required as the flasher image detection has improved.

**Comment by pimterry** [comment]
I think this is done now with that linked PR, right? I'm going to close it, shout if that's wrong.

Generally @zvin you don't need to create issues like this for the CLI. Issues here (and in the SDK etc) are good for planning work or bug fixes that need doing one day in the future, but you don't need one before opening a PR that's totally self-explanatory. We're not using waffle at all, mainly because there's no need to track done vs released when they're the same thing.

For things like this, you can just open a PR and get it merged, that's all that's required.

**Comment by zvin** [comment]
Thanks @pimterry I forgot to close it.
I'll make PRs directly in the future.
