### ISSUE TITLE
"Stopping and removing container" can take a long time

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-cli#760]
Related to https://github.com/resin-io/resin-cli/issues/723

It seems like containers can take an longer amount of time to stop and remove than they probably should, e.g. 10mins for a Gb image on an intel nuc. 

Resin-CLI version 6.12.5

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6v3l)

**Comment by danielmahon** [comment]
This happens EVERY time `resin local` does a build or `--force-build`. Bascially making the tool useless. Im not sure what it's getting stuck on. Same issue if I change the `app-name` in `.resin-sync.yml` as well.

**Comment by pimterry** [comment]
@danielmahon one of the main issues here is the UX: when this operation is running it isn't just stopping & removing containers, it's actually also querying the remote docker (which should be pretty quick) and uploading your local build context to the device.

I think in every case I've seen the slowdown here is because you're uploading more files in your build context that you need. Do you have any large files or folders in the directory you're building? I've especially seen this with `node_modules` and friends - if you remove those locally or ignore them, and instead install dependencies only in your dockerfile, everything should go much quicker.

**Comment by pimterry** [comment]
I'm going to close this. I'm pretty sure generally this time is being taken up by build context uploads, and https://github.com/resin-io-modules/resin-sync/pull/147 should now make that much clearer.

Further improvements to performance & UX of that will happen in https://github.com/resin-io/resin-cli/issues/528, but generally the answer is to reduce the size of your build context, so there's just less to send over the wire (and for us to ignore things like node_modules by default: https://github.com/resin-io/resin-cli/issues/683). 

Feel free to ping here and we can reopen if there are indeed further issues with the time to stop & remove containers after reinstalling the CLI, but as far as I can tell that should be a very fast operation everywhere now.
