### ISSUE TITLE
CLI install fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by nckswt** [resin-io/resin-cli#776]
- **resin-cli version:** 6.12.7. 
- **Operating system and architecture:** Ubuntu 16.04 running on a partition of a Macbook Pro
- **nodejs version:** v4.2.6

When I follow [the official install docs](https://docs.resin.io/tools/cli/) and run `sudo npm install --global --production resin-cli` on a Ubuntu 16.04 machine, installation fails because a problem occurs with `node-gyp`. Here's [the gist](https://gist.github.com/nckswt/9ca0b4639cd82e31750683060956f2b7).

You'll also see `/usr/bin/env: ‘node’: No such file or directory; /bin/sh: 1: node: not found` in the gist. I don't know if the problem's related, but I fixed that problem with a `sudo ln -s /usr/bin/nodejs /usr/bin/node` (might need to update documentation for some users if this is a problem?)

Is there an easy fix? Can I provide any more debugging output that might be helpful?

**Comment by nckswt** [comment]
I was able to get around this by running `sudo npm install --global --production --unsafe-perm resin-cli`. I suspect that this is due to a version incompatibility, since `sudo apt-get install npm` defaults to `v4.2.6`, instead of `v6.0.0` that resin expects. [Installing npm via a ppa](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04) would likely be a better approach.

Leaving this issue here in case anyone else has the same issue!

**Comment by pimterry** [comment]
Thanks for the report @nckswt. You're right - Resin CLI requires Node >= 6, so this would always fail without upgrading. I'm surprised it fails in this particular way though, I thought `node` was the standard binary name everywhere.

Regardless, I'm not going to worry about this too much both because Ubuntu 17.10 does have Node 6.11 preinstalled, and because fairly soon we're migrating towards not requiring node installed locally at all (see 'Standalone Install' in the readme - still experimental, but largely working everywhere already), which will resolve this completely.

I'm going to close this issue, as there's no CLI action required here, but do ping if you think there's anything we should do about this in the short term. Thanks again for filing this though, it's definitely a useful note for us, and others who might hit this in future.
