### ISSUE TITLE
Proposal: offer ability to remember wifi credentials in CLI/quickStart

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#78]
Could be cool to allow the quickstart to remember wifi credentials similar to the way the browser does, as it gets annoying entering this everytime (i am lazy)

**Comment by emirotin** [comment]
Actually the browser (did you mean the UI?) doesn't remember them because when it was discussed the security concern (legit) was raised and it was agreed to not remember this sensitive info. Though with proper confirmation and taking into account the data are stored locally that should be OK for the CLI

**Comment by shaunmulligan** [comment]
I was talking more about how chrome browser remembers my wifi passwords for me, so i dont have to retype it when i provision rpi :+1:

**Comment by emirotin** [comment]
Oh, ok :)

**Comment by jviotti** [comment]
Closing as low priority for now.
