### ISSUE TITLE
resin installed in userland, not available as root

### ISSUE THREAD

**Issue by arthurlutz** [resin-io/resin-cli#798]
- **resin-cli version:** : 6.13.4
- **Operating system and architecture:** : ubuntu amd64

I have an NPM configuration that enables me to do install npm -g in userland : 

```
export NPM_PACKAGES="/home/arthur/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules${NODE_PATH:+:$NODE_PATH}"
export PATH="$NPM_PACKAGES/bin:$PATH"
```

For resin the consequence is this : 

```
arthur@black:~/local/resin/test$ resin config inject config.json --type raspberry-pi --drive ~/Downloads/resin-musicboxrpi-2.9.6+rev1-dev-v6.5.9.img
You don't have enough privileges to run this operation.
Try running this command again prefixing it with `sudo`.

If this is not the case, and you're trying to burn an SDCard, check that the write lock is not set.

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io

arthur@black:~/local/resin/test$ sudo resin config inject config.json --type raspberry-pi --drive ~/Downloads/resin-musicboxrpi-2.9.6+rev1-dev-v6.5.9.img
[sudo] password for arthur: 
sudo: resin: command not found
```

By the way, I can't find a way to replay the command to see which command would need sudo, which would be nice (this is probably another issue). 

I guess this is related to #385

**Comment by pimterry** [comment]
@arthurlutz Hmm, that's interesting. I suspect it's just because your `sudo` doesn't inherit your PATH, and you don't have an equivalent PATH setup for the root user. There's some suggestions here: https://unix.stackexchange.com/questions/83191/how-to-make-sudo-preserve-path.

This isn't really a resin CLI problem - if you want to be able to run any node cli apps as root, you'll need to sort this path out - so I'm going to close this as an issue. Feel free to comment here if you've got any other questions though, or if you do think there's something we should be doing to handle this on our end.

You might be interested to take a look at the standalone install option too (see [the readme](https://github.com/resin-io/resin-cli#standalone-install)), which doesn't require npm at all, and would let you avoid this issue. That's still experimental, and might not work in all cases, but that's the medium term plan for the cli, in part because it'll solve issues like this entirely.
