### ISSUE TITLE
resin-cli is overriding system sudo

### ISSUE THREAD

**Issue by lordfuoco** [resin-io/resin-cli#800]
- **resin-cli version:** 6.13.4
- **Operating system and architecture:** OSX High Sierra 10.13.1

Today I discovered that resin-cli depends and installs this node module:
https://www.npmjs.com/package/president

That in turn depends and installs:
https://www.npmjs.com/package/windosu

Which add a bin called:**sudo**

So since resin-cli needs to be globally installed that bin called **sudo** ends up globally installed as well ( at least if you are installing with yarn but I believe is the same approach as npm)

And now the system **sudo** does not work anymore. 
Because winsudo is for windows.

And in general no-global package should install something that override a basic system tool like sudo especially the one that is needed to escalate system privileges and that takes the system password as an input.

I am a JS developer myself and I know that not much attention is paid to the node module hierarchy but this is a global cli package.

Now the workaroud to keep using resin is to add an alias:

```bash
sudo="/usr/bin/sudo "
```

*note the space after the word sudo

But this issue needs to be addressed.

**Comment by pimterry** [comment]
@lordfuoco thanks for the report. I'm still investigating, but this definitely isn't something that affects most users. This hasn't changed recently, lots of people install resin-cli globally on various platforms, and quite a few commands are only runnable with `sudo`, and are being used successfully, so we definitely would've heard if this was broken everywhere.

That limits the severity, but doesn't help your case of course. The easy first key fix is to put your npm bin path at the end of your `PATH`, not the start. If you do that, no npm package will ever be able to do this, since existing binaries will take precedence.

On my linux machine (using nvm with npm 4.6.1) when I install resin-cli it does install the windosu package globally, but it doesn't install the windosu binary globally. The only file added to `<node_install>/bin` is `resin-cli`. I suspect this is the correct behaviour, so this shouldn't be happening at all, though I can't find anything to confirm that anywhere.

If you uninstall, and reinstall with `npm`, do you see this same behaviour? It'd be interesting to know your `yarn`, `npm` and `node` versions to investigate further.

**Comment by lordfuoco** [comment]
@pimterry 
So I did few experiments:
yarn version: 1.3.2

```bash
yarn remove resin-cli
cat /usr/local/bin/sudo -> No such file of directory
yarn add resin-cli
cat /usr/local/bin/sudo -> No such file of directory
yarn global upgrade
cat /usr/local/bin/sudo -> file is there
```

So apparently a normal install of resin does not do any problem, but asking yarn to upgrade your global packages create the problem.

this may not be resin-cli problem but I got this only after resin was installed.

**Comment by lordfuoco** [comment]
@pimterry 
Updated to yarn 1.5.1
same behaviour

**Comment by pimterry** [comment]
@lordfuoco do you mean `yarn global add` there? You don't have `global` above.

Assuming that's true, this sounds a lot like a clear yarn bug to me. When you install a global package, I don't think all its dependencies' binaries should be installed globally too, and it definitely seems like that behaviour doesn't match `npm`. This seems like something that's going to break with a lot of other CLI packages too, as they'll now install a selection of other random binaries into your PATH as well.

Can you file a bug with Yarn and see what they say? Our options otherwise are a bit limited - the `windosu` binary isn't actually used in `president` (it requires the library, and uses `windosu.exec(...)` on windows), but we'd need to do some substantial forking our dependencies to rerelease them and avoid having this installed incidentally.

In the medium-term this won't matter either way, as we're looking towards deprecating the npm/yarn install approach entirely, and distributing a standalone binary instead, which would skip this whole problem. There's details in the readme if you're interested, though it's a little experimental right now.

**Comment by lordfuoco** [comment]
@pimterry my bad yes `yarn global add and yarn global remove` I just mistyped.
I will definitively fill up a bug with yarn and link it here for reference.
Thank you for the quick help, much appreciated! 

I am very much looking forward to the standalone binary that seems a solid approach.

**Comment by lordfuoco** [comment]
@pimterry as a reference here is the issue on yarn 
https://github.com/yarnpkg/yarn/issues/5441

**Comment by pimterry** [comment]
Great, thanks @lordfuoco. Given that, I'm going to close this issue for now. This is a Yarn bug, with some good workarounds, and we're going to solve it completely once #484 is all finished.

Feel free to ping here if the Yarn team disagree though, or if there's anything else we can do on our end.
