### ISSUE TITLE
Spinner for Image Download and indicate that it will take a while...

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#90]
In the `Configuring device operating system image` step it would probably be good to have a random spinner, while the download happens. Also indicate that this step may take a minute or two.

**Comment by jviotti** [comment]
> it would probably be good to have a random spinner, while the download happens.

This is currently the case. If we know the size of the download we show a progress bar, otherwise a spinner. I believe this concern was raised before this was implemented, therefore ignoring this part as "done".

>  Also indicate that this step may take a minute or two.

I agree with this. Let's print a message right below `Configuring device operating system image` for it.
