### ISSUE TITLE
Unable to build image with RUN statement in Dockerfile

### ISSUE THREAD

**Issue by Vinno97** [resin-io/resin-cli#904]
- **resin-cli version:** 7.6.0
- **Operating system and architecture:** Ubuntu 18.04

Hi, I am having trouble building a images from Dockerfiles. I cannot use the `RUN` command in a Dockerfile while using `resin build`. For some reason the the command and its parameters are treated like they're scripts. 

When I commit my changes and run `git push resin master`, the build _does_ succeed.

---

The following example is enough to make it fail:

```dockerfile
FROM resin/raspberry-pi2-node

RUN true
```

When I then run `resin build`, the following error appears:

```terminal
$ resin build --deviceType raspberrypi2 --arch armhf
[Info]    Compose file detected
[Info]    Building for armv7hf/raspberry-pi2
[Build]   Built 1 service in 0:01
[Build]   test [==========>          ]  50% Step 2/4: standard_init_linux.go:190: exec user process caused "no such file or directory"
[Error]   Build failed
The command '/bin/sh -c true' returned a non-zero code: 1

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io
```

P.S. I do make use of a `docker-compose`-file, but I don't think this is the reason.

**Comment by pimterry** [comment]
@Vinno97 the problem here is that you're building an ARM base image, filled with ARM binaries, but running them on an x86 machine. Lots of things on this base image will implode by default, since they're not built to run on your architecture.

You can fix this by passing the `--emulated`/`--e` argument to `resin build`, which will emulate the target architecture for your RUN commands, so they work correctly on your local machine. That should solve this immediately, but feel free to shout if it doesn't.
