### ISSUE TITLE
Could not find any resinOS devices in the local network

### ISSUE THREAD

**Issue by jhabdas** [resin-io/resin-cli#905]
- **resin-cli version:** 7.6.0
- **Operating system and architecture:** Darwin mbp 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

<img width="650" alt="screen shot 2018-06-25 at 8 14 18 pm" src="https://user-images.githubusercontent.com/440298/41849694-69eb1182-78b4-11e8-9ec7-a123010af406.png">

I've got a Pi3 running resinOS on a _public_ WiFi network and local mode doesn't seem to be working. The device shows up in the dashboard okay but is nowhere to be found when I scan the local network or attempt to ping it.

Is there a way to spoof the MAC address so I can determine if my device is being hidden?

**Comment by jhabdas** [comment]
I tried forcing a static IP and that worked—the dashboard updated. But the device still doesn't appear on this particular (public) WiFi network nor does it respond to ping requests for debugging purposes. I'll take this to [the forums](https://forums.resin.io/) should the problem persist on other networks.

**Comment by pimterry** [comment]
Local mode scanning works using MDNS, which shares DNS information over multicast on the network. It's possible something on this specific network caused issues with that. Since you're having trouble connecting to the IP directly, I expect this network is simply refusing the route any traffic between devices on the network, and only from devices through to the outside world.

Right now, that means there aren't really any easy ways to use local mode, since there's simply no way for your machine to connect to the device at all. I'm afraid you'll either need to reconfigure the network, set up your own network that does allow this, or just deploy through the resin.io cloud service (which allows devices to pull updates, and uses a VPN connection to quickly notify them when they need to do so).

In general btw, you probably don't want to use a development mode image on a public network at all - doing so typically exposes direct SSH & Docker access to anybody else on the network, so that with minimal effort they could take control of the device completely.

**Comment by jhabdas** [comment]
> Since you're having trouble connecting to the IP directly, I expect this network is simply refusing the route any traffic between devices on the network, and only from devices through to the outside world.

Thanks for the info. The odd part was the local machine showed up one time out of 10 when I scanned for it and I was able to SSH into the box. As soon as I exited the shell it was no longer accessible.

> I'm afraid you'll either need to reconfigure the network, set up your own network that does allow this [...].

Done. I switched to a more private network, set-up my own private network using a spare Asus router, created a new app in the resin.io dashboard, pushed up the `simple-server-node` example, tested again from an external URL with success and then enabled local mode and got the same result. I then backed down from Node 10 to Node 8.4, updated to the the latest version of the `resin-cli` and rescanned and still could not find any resinOS devices in the local network.

Worth noting is that I was able to use local mode from this device fine until a few days ago. Both the last network I was on (the public one) and my current private network connected to ZTE routers.

Given both routers were ZTE routers and I'm in a country which censors I'd like to run some tests. Running `local scan` with the `--verbose` flag doesn't provide any extra detail and I'm not about to drop into the source right now. If you know of any specific I can run to determine what's stifling my workflow please let me know.

**Comment by jhabdas** [comment]
Thanks for the info. The odd part is I tried my private network which was working before and it's not working now either. If you know if any debugging or diagnostic suggestions please let me know as connecting via Web isn't suitable for application development with resinOS imo.

**Comment by jhabdas** [comment]
It's working now. I'd been putting off an upgrade to macOS and now that I upgraded the `scan local` command has no issues finding the resin device now (seriously).

> Local mode scanning works using MDNS, which shares DNS information over multicast on the network. It's possible something on this specific network caused issues with that.

That's very useful to know. Thank you kindly for your help.

**Comment by pimterry** [comment]
Huh, that's very weird. Ok, glad you've got it sorted! I'll keep an eye out for this, and take a closer look if we get any more reports of the same thing. Let us know if you have any other problems.
