### ISSUE TITLE
Getting: Invalid volume signature! for jetson-tx2/2.13.0+rev1

### ISSUE THREAD

**Issue by ofirule** [resin-io/resin-cli#908]
- resin-cli@7.6.1
- Ubuntu 16.04 x86-64

      $ sudo resin local configure resin.img
       Invalid volume signature!

      If you need help, don't hesitate in contacting us at:

      GitHub: https://github.com/resin-io/resin-cli/issues/new
      Forums: https://forums.resin.io

tried it with Raspberry Pi 3 img and it didn't reproduce

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_cnnv)

**Comment by pimterry** [comment]
@telphan Any idea what's up here? Has anything changed in the partition layout for the TX2 recently that might have started causing this?

**Comment by floion** [comment]
@pimterry the boot partition on the tx2 is 12.
I think the CLI should adapt to that, probably still uses partition 1 for this board?

**Comment by pimterry** [comment]
> the boot partition on the tx2 is 12.

@floion is that true?  [https://api.resin.io/config](https://api.resin.io/config) for the tx2 has:

```json
"configuration": {
	"config": {
		"partition": {
			"primary": 1
		},
		"path": "/config.json"
	}
}
```

and `parted <tx2 2.13.0+rev1.prod>` gives me:

```
Number  Start   End     Size    File system  Name         Flags
 1      4194kB  88.1MB  83.9MB  fat16        resin-boot   boot, esp
 2      88.1MB  3238MB  3150MB  ext4         resin-rootA
 3      3238MB  3242MB  4194kB  ext4         resin-rootB
 4      3242MB  3246MB  4194kB               resin-state
 5      3246MB  3262MB  15.7MB               resin-data
```

I've had a look at this - it actually _does_ seem to work with `os configure` (I think on partition 1), and just fails with `local configure`. I think the issue is that we're using an old version of reconfix (and thereby resin-image-fs) in there. 

I'm going to update that and do some testing, but it looks like that should fix it, unless I'm missing something?
